name: rinus
favicon: null
layout_spectrum: 0.6048056816216558
typography_spectrum: 0.7299974062480032
title: The Journey to Total Football
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3e2dd'
    - '#172315'
    - '#22502b'
    - '#99aea7'
    - '#3c693e'
  brandStrength: 1
  lightness: 0.16987842111848295
  saturation: 0
  rhythmicContrast: 0.5974039542488754
purpose: []
