name: rinus
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72713
title: The Journey to Total Football
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f4447'
    - '#788b5e'
    - '#c8d1e0'
    - '#a8adb1'
  brandStrength: 0.4881848
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5974039542488754
purpose: []
